// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKSlXbeTAj2i6faQH8GtnQThapCLGJek',
    appId: '1:132642664690:web:dd51fec0d729130e7f206b',
    messagingSenderId: '132642664690',
    projectId: 'major-project-921f6',
    authDomain: 'major-project-921f6.firebaseapp.com',
    storageBucket: 'major-project-921f6.appspot.com',
    measurementId: 'G-H1WF9JXRPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAP8xlZ7pdeiv3hbDUXpWdrb2ymazDUoY',
    appId: '1:132642664690:android:73ac7c34d03477f07f206b',
    messagingSenderId: '132642664690',
    projectId: 'major-project-921f6',
    storageBucket: 'major-project-921f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtyDxtQ3HbMpXe2Lc_lfF091I1TsZHZiU',
    appId: '1:132642664690:ios:a3eb6aab17e65f117f206b',
    messagingSenderId: '132642664690',
    projectId: 'major-project-921f6',
    storageBucket: 'major-project-921f6.appspot.com',
    iosClientId: '132642664690-c9surcgnqa998qpmc1mvua42m1l9c4ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorTry',
  );
}
